### ISSUE TITLE
[Learn]: I typed (?<=\$)\d+ in answer and nothing.

### ISSUE THREAD

**Issue by zhekazuev** [aykutkardas/regexlearn.com#155]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `ru`
**Version:** `v2.3.1`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15`

---

**What is the problem you are experiencing?**
I typed (?<=\$)\d+ in answer and nothing.

I use inspect to show input: 
<input type="text" class="InteractiveArea_InteractiveAreaInput__3E-52" style="width: 150px;" placeholder="regex" spellcheck="false" value="(?<=\$)\d+">

I changed language to EN and I have these problem too.

**Comment by zhekazuev** [comment]
I use inspect to show input:
```html
<input type="text" class="InteractiveArea_InteractiveAreaInput__3E-52" style="width: 150px;" placeholder="regex" spellcheck="false" value="(?<=\$)\d+">
'''

**Comment by aykutkardas** [comment]
Actually the problem is in the browser. This feature is not supported by safari. If you normally use safari, a highlighted warning will appear and ask you to click to skip these steps. But if this warning does not appear, it means there is a problem with the code detecting the browser.

In a few hours, I will release an update that will allow you to skip these steps.

**Comment by zhekazuev** [comment]
I normally use Safari every day(I think problem with Safari).
But warning does not appear. Maybe I need to wait 5 minutes or more?

It will be good - if I can skip some steps.
Thank you!

**Comment by aykutkardas** [comment]
Can you try again?

**Comment by zhekazuev** [comment]
Cool.
