### ISSUE TITLE
[Learn]: The regex expression of the "negated character set" from the cheatsheet doesn't work in exercise 13

### ISSUE THREAD

**Issue by Asbestasyoucan** [aykutkardas/regexlearn.com#178]
**Step Number:** `12`
**Step Name:** `examples.negatedCharacterSet.title`
**Language:** `en`
**Version:** `v2.5.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36`

---

The regex expression of the "negated character set" from the cheatsheet doesn't work in exercise 13 when modified to the specific task.

/b[^ou]r/   doesn't do anything

/b[^ou]+r/   though still incorrect for the task does highlight "bear" and "beer"

**Comment by aykutkardas** [comment]
If you solve the question differently from the tutorial, it will still be highlighted but in yellow. And you cannot proceed to the next step.

It is correct and highlighted in the answer below. But it's not green because it's not the answer the tutorial wanted and won't let you go to the next step.

`/beer|bear/`
