### ISSUE TITLE
[Learn]: Positive lookbehind

### ISSUE THREAD

**Issue by omarozt** [aykutkardas/regexlearn.com#40]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**

Even if the answer from the show answer button is entered, it doesnt match. 
Browser: Safari 15

**Comment by aykutkardas** [comment]
Safari doesn't support these features, so I made an edit to get you past this step of the tutorial. Changes caused by the expression you typed cannot be displayed.

However, in order to proceed to the next step, it is tested whether the expression you wrote is correct.

Refresh the page and try again.
