### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by Dexter1203** [aykutkardas/regexlearn.com#408]
**Step Number:** `39`
**Step Name:** `steps.withoutWordCharacter.title`
**Language:** `zh-cn`
**Version:** `v2.30.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0`

---

**What is the problem you are experiencing?**

answer shuold incloude "[^\w]"

**Comment by aykutkardas** [comment]
This step teaches you \W. So that has to be the answer. If you use [^\w] you will see the characters highlighted in yellow. This means that the answer is technically correct but wrong for the step being taught.

![CleanShot 2024-11-15 at 12 08 00@2x](https://github.com/user-attachments/assets/63f10339-5598-44cf-b254-7a54bef6c57c)
